[google_oauth]
client_id = "10381255713-pncgg5qj1gkh6slmouhljris6e57sv8p.apps.googleusercontent.com"
project_id = "tailortalk-calendar-app"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
redirect_uris = ["http://localhost"]
