[google_token]
token = "ya29.a0AS3H6Ny5oCQJhe58kRQQBvVe3yRIOj8VdfFuGzjN9zQWWQM4ns0LJuL--QW7OegFDHXO__2QwGxxZESaKG8-pd7kU_8ldydOMqCo3pQFXpZ4d7xwH-vHUvxPEy_ivXzgdFsWRJ3MsKD-LRIOKoWoGLzb5n3UCezmA8iQ0JUhLgaCgYKAScSARQSFQHGX2MiC9ZKtMzHtMJ6DIBverw-ig0177"
refresh_token = "1//0geNbYc4Jcp73CgYIARAAGBASNwF-L9IrTGAT8YlixsLFctOUDn6qQq5NPrcFB0SXGk__8vwnLjGYm6J_k_bsUadUSeq_x3Do-s4"
token_uri = "https://oauth2.googleapis.com/token"
client_id = "10381255713-pncgg5qj1gkh6slmouhljris6e57sv8p.apps.googleusercontent.com"
client_secret = "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"
scopes = ["https://www.googleapis.com/auth/calendar"]

